In [55]:
import json
import pandas as pd
from collections import Counter

# Load JSONL into pandas
records = []
with open("data/all_providers_results_parallelized.jsonl", "r") as f:
    for line in f:
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as e:
            print("Bad line:", e)
df = pd.DataFrame(records)

print(f"✅ Loaded {len(df)} rows")
print(df.columns.tolist())

✅ Loaded 2294 rows
['index', 'question', 'choices', 'correct_answer', 'gemini-2.5-flash-lite_response', 'meta-llama_Llama-3.2-11B-Vision-Instruct_response', 'google_gemma-3n-E4B-it_response', 'openai_gpt-oss-20b_response', 'nvidia_NVIDIA-Nemotron-Nano-9B-v2_response', 'accounts_fireworks_models_kimi-k2-thinking_response', 'openai_gpt-oss-120b_response', 'gpt-5-nano-2025-08-07_response', 'grok-4-fast-reasoning_response']

In [56]:
# Count occurrences of each model key
model_columns = [c for c in df.columns if c.endswith('_response')]
print(f"Models detected ({len(model_columns)} total):")
for m in model_columns:
    print("-", m)

Models detected (9 total):
- gemini-2.5-flash-lite_response
- meta-llama_Llama-3.2-11B-Vision-Instruct_response
- google_gemma-3n-E4B-it_response
- openai_gpt-oss-20b_response
- nvidia_NVIDIA-Nemotron-Nano-9B-v2_response
- accounts_fireworks_models_kimi-k2-thinking_response
- openai_gpt-oss-120b_response
- gpt-5-nano-2025-08-07_response
- grok-4-fast-reasoning_response

In [57]:
counts = {m: df[m].notna().sum() for m in model_columns}
for m, c in counts.items():
    print(f"{m}: {c}")

gemini-2.5-flash-lite_response: 400
meta-llama_Llama-3.2-11B-Vision-Instruct_response: 400
google_gemma-3n-E4B-it_response: 400
openai_gpt-oss-20b_response: 400
nvidia_NVIDIA-Nemotron-Nano-9B-v2_response: 400
accounts_fireworks_models_kimi-k2-thinking_response: 400
openai_gpt-oss-120b_response: 400
gpt-5-nano-2025-08-07_response: 400
grok-4-fast-reasoning_response: 400

In [58]:
import pandas as pd
from IPython.display import display

# Make sure all expected columns exist
for m in model_columns:
    if m not in df.columns:
        df[m] = None

# 1. Group by question index
grouped = df.groupby("index")

# 2. Identify incomplete indices (missing any model response)
incomplete_indices = []
for idx, group in grouped:
    found_models = [m for m in model_columns if group[m].notna().any()]
    if len(found_models) < len(model_columns):
        incomplete_indices.append(idx)

print(f"Total incomplete indices: {len(incomplete_indices)}")
print("First few:", incomplete_indices[:20])

# 3. Gracefully handle empty case
if not incomplete_indices:
    print("\n✅ All indices appear complete after merging.")
else:
    # Pick one incomplete index to inspect
    idx = incomplete_indices[0]
    group = grouped.get_group(idx)
    print(f"\n--- Inspecting index {idx} ---")

    # 4. Merge all fragments (later rows overwrite earlier)
    merged = group.iloc[0].copy()
    for m in model_columns:
        vals = group[m].dropna().tolist()
        if vals:
            merged[m] = vals[-1]  # take most recent non-null

    # 5. Display all responses neatly
    cols_to_show = ["index", "question", "correct_answer"] + model_columns
    pd.set_option("display.max_colwidth", 200)
    display(merged[cols_to_show].to_frame().T)

Total incomplete indices: 0
First few: []

✅ All indices appear complete after merging.

In [59]:
import json
import pandas as pd
from IPython.display import display, HTML

# Load JSONL
records = []
with open("data/all_providers_results_parallelized.jsonl") as f:
    for line in f:
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            pass

df = pd.DataFrame(records)

# Group by question index
grouped = df.groupby("index")

def show_group(idx, group):
    """Render one question group neatly."""
    model_cols = [c for c in group.columns if c.endswith("_response")]
    q = group.iloc[0]  # question text and choices (same within group)

    html = f"""
    <h3>Question index: {idx}</h3>
    <p><b>Question:</b> {q['question']}</p>
    <p><b>Choices:</b> {q['choices']}</p>
    <p><b>Correct answer:</b> {q['correct_answer']}</p>
    """

    rows = []
    for _, row in group.iterrows():
        for m in model_cols:
            if m in row and pd.notna(row[m]):
                val = row[m]
                if isinstance(val, dict):
                    answer = val.get("answer", str(val))
                    input_tokens = val.get("input_tokens", "N/A")
                    output_tokens = val.get("output_tokens", "N/A")
                    first_token_latency = val.get("first_token_latency", "N/A")
                    total_latency = val.get("total_latency", "N/A")
                    
                    # Format latency values
                    if isinstance(first_token_latency, (int, float)):
                        first_token_latency = f"{first_token_latency:.3f}s"
                    if isinstance(total_latency, (int, float)):
                        total_latency = f"{total_latency:.3f}s"
                    elif total_latency is None:
                        total_latency = "N/A"
                else:
                    answer = str(val)
                    input_tokens = "N/A"
                    output_tokens = "N/A"
                    first_token_latency = "N/A"
                    total_latency = "N/A"
                
                rows.append({
                    "Model": m.replace("_response", ""),
                    "Answer": answer,
                    "Input Tokens": input_tokens,
                    "Output Tokens": output_tokens,
                    "First Token Latency": first_token_latency,
                    "Total Latency": total_latency
                })
    table = pd.DataFrame(rows)

    html += table.to_html(index=False, escape=False)
    html += "<hr>"
    display(HTML(html))

# Display first 10 unique indices (grouped)
for i, (idx, group) in enumerate(grouped):
    show_group(idx, group)
    if i == 9:
        break

In [60]:
import pandas as pd
import numpy as np
from IPython.display import display

# Make sure all model columns exist
for m in model_columns:
    if m not in df.columns:
        df[m] = np.nan

# Helper to detect errors in strings or dicts
def is_error(value):
    if pd.isna(value):
        return False
    if isinstance(value, str):
        val_str = value.strip()
        # Check for "Error:" prefix or error-like patterns
        if val_str.startswith("Error:") or "Error" in val_str or "ConnectionResetError" in val_str:
            return True
    elif isinstance(value, dict):
        # Check if dict has an error field or error in answer
        if "error" in value or (isinstance(value.get("answer"), str) and "Error" in value.get("answer", "")):
            return True
    return False

# Group by index and merge responses from different rows
grouped = df.groupby("index")
issues = []

for idx, group in grouped:
    # Merge all model responses for this index (take last non-null value)
    merged_row = group.iloc[0].copy()
    for m in model_columns:
        vals = group[m].dropna().tolist()
        if vals:
            merged_row[m] = vals[-1]  # take most recent non-null
    
    # Check each model for missing/error responses
    question_text = merged_row.get("question", "")[:120] + "..." if len(merged_row.get("question", "")) > 120 else merged_row.get("question", "")
    
    for m in model_columns:
        val = merged_row.get(m, None)
        if pd.isna(val) or is_error(val):
            issues.append({
                "index": idx,
                "model": m,
                "issue_type": "missing" if pd.isna(val) else "error",
                "question": question_text,
                "value": str(val)[:100] + "..." if val and len(str(val)) > 100 else str(val) if val else None
            })

issues_df = pd.DataFrame(issues)

# --- summary ---
if issues_df.empty:
    print("✅ No missing or error responses found.")
else:
    print(f"⚠️ Found {len(issues_df)} issues across {issues_df['index'].nunique()} questions.")
    print("\n" + "="*60)
    print("Issue type breakdown:")
    print("="*60)
    print(issues_df["issue_type"].value_counts())
    
    # Group errors by model
    print("\n" + "="*60)
    print("Issues grouped by Model:")
    print("="*60)
    model_summary = issues_df.groupby("model").agg({
        "index": "count",
        "issue_type": lambda x: dict(x.value_counts())
    }).rename(columns={"index": "total_count", "issue_type": "breakdown"})
    model_summary = model_summary.sort_values("total_count", ascending=False)
    display(model_summary)
    
    # Group errors by error value/message (for actual errors, not missing)
    error_df = issues_df[issues_df["issue_type"] == "error"].copy()
    if not error_df.empty:
        print("\n" + "="*60)
        print("Errors grouped by Error Message:")
        print("="*60)
        # Extract error message pattern (first part before colon or first 50 chars)
        def extract_error_pattern(x):
            if not x:
                return "Unknown"
            x_str = str(x)
            if ":" in x_str:
                return x_str.split(":")[0].strip()
            return x_str[:50].strip()
        
        error_df["error_pattern"] = error_df["value"].apply(extract_error_pattern)
        error_grouped = error_df.groupby("error_pattern").agg({
            "index": ["count", lambda x: sorted(list(x))[:5]],
            "model": lambda x: sorted(list(x.unique()))[:5]
        })
        error_grouped.columns = ["count", "sample_indices", "sample_models"]
        error_grouped = error_grouped.sort_values("count", ascending=False)
        display(error_grouped)
    
    # Group by model and issue_type (cross-tabulation)
    print("\n" + "="*60)
    print("Issues grouped by Model and Issue Type (Cross-tabulation):")
    print("="*60)
    model_issue_crosstab = pd.crosstab(issues_df["model"], issues_df["issue_type"], margins=True)
    display(model_issue_crosstab)
    
    print("\n" + "="*60)
    print("First few problematic rows:")
    print("="*60)
    display(issues_df.head(20))

⚠️ Found 1 issues across 1 questions.

============================================================
Issue type breakdown:
============================================================
issue_type
error    1
Name: count, dtype: int64

============================================================
Issues grouped by Model:
============================================================

                                total_count     breakdown
model
gpt-5-nano-2025-08-07_response            1  {'error': 1}

============================================================
Errors grouped by Error Message:
============================================================

               count sample_indices                     sample_models
error_pattern
Error              1          [236]  [gpt-5-nano-2025-08-07_response]

============================================================
Issues grouped by Model and Issue Type (Cross-tabulation):
============================================================

issue_type                      error  All
model
gpt-5-nano-2025-08-07_response      1    1
All                                 1    1

============================================================
First few problematic rows:
============================================================

,index,model,issue_type,question,value
0,236,gpt-5-nano-2025-08-07_response,error,They think they're lucky that they're living and it's Christmas again. They can't see that we live on a dirty street in ...,Error: peer closed connection without sending complete message body (incomplete chunked read)